  server:
    port: 8000

  spring:
    mvc:
      static-path-pattern: /static/**

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://web-study.cf6og1l7mjlg.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-yeonho?allowMultiQueries=true
      username: admin
      password: 1q2w3e4r!

    security:
      user:
        name: admin
        password: 1q2w3e4r

  mybatis:
    mapper-locations:
      - /mappers/*.xml
